version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    # command: ["make", "dev"]
  
  # caddy:
  #   image: caddy:2.8.4
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - "app"
  #   volumes:
  #     - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
