version: '3.8'

services:
  php:
    build:
      context: .
  app:
    image: ruslan0688/vtiger-app
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
  www:
    image: php:7.4-apache
    volumes:
      - "./app:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 8083:80
      - 443:443 # for future ssl traffic

volumes:
  db-data: